# Generated by Django 4.1.2 on 2022-10-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rodzaj', models.TextField(blank=True, null=True)),
                ('czopki_czy_globulki', models.TextField(blank=True, null=True)),
                ('ilosc_czop_glob', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('masa_docelowa_czop_glob', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('czy_ilosc_oleum_pomnozyc', models.TextField(blank=True, null=True)),
                ('ilosc_masci', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('ilosc_gramow', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skladnik', models.CharField(max_length=40)),
                ('jednostka_z_recepty', models.CharField(blank=True, default='gramy', max_length=40)),
                ('ilosc_na_recepcie', models.CharField(blank=True, default='0', max_length=40, null=True)),
                ('gramy', models.CharField(default='0', max_length=40)),
                ('mililitry', models.CharField(default='0', max_length=40)),
                ('solutio', models.CharField(default='0', max_length=40)),
                ('krople', models.CharField(default='0', max_length=40)),
                ('opakowania', models.CharField(default='0', max_length=40)),
                ('jednostki', models.CharField(default='0', max_length=40)),
                ('gestosc', models.CharField(default='0', max_length=40)),
                ('sztuki', models.CharField(default='0', max_length=40)),
                ('tabletki', models.CharField(default='0', max_length=40)),
                ('czesci', models.CharField(default='0', max_length=40)),
                ('producent', models.CharField(default='0', max_length=40)),
                ('aa', models.CharField(default='off', max_length=20)),
                ('obey', models.IntegerField(default=0, null=True)),
                ('sumg', models.IntegerField(default=0)),
                ('aa_ad', models.CharField(default='off', max_length=20)),
                ('aa_ad_gramy', models.CharField(default='0', max_length=40)),
                ('show', models.BooleanField(default=True)),
                ('dodaj_wode', models.CharField(default='off', max_length=20)),
                ('pozadane_stezenie', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('uzyte_stezenie', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('ilosc_etanolu', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('ilosc_wody_do_etanolu', models.CharField(blank=True, default='0', max_length=40, null=True)),
                ('qs', models.CharField(default='off', max_length=20)),
                ('ad', models.CharField(default='off', max_length=20)),
                ('woda_mocznik', models.CharField(default='0', max_length=40)),
                ('UI_w_mg', models.CharField(default='6756', max_length=40)),
                ('czy_zlozyc_roztwor_ze_skladnikow_prostych', models.CharField(default='off', max_length=20)),
                ('woda_kwas_borowy', models.CharField(default='0', max_length=40)),
                ('ilosc_kwasu_borowego_do_roztworu', models.CharField(default='0', max_length=40)),
                ('calkowita_ilosc_gramow_wody', models.CharField(default='0', max_length=40)),
                ('czy_powiekszyc_mase_oleum', models.CharField(default='off', max_length=20)),
                ('gramy_czystej_vit_e', models.CharField(default='0', max_length=20)),
                ('gramy_roztworu', models.CharField(default='0', max_length=20)),
                ('receptura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.receptura')),
            ],
        ),
    ]
