# Generated by Django 4.1.2 on 2023-01-29 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptura',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 11, 9, 7, 219898, tzinfo=datetime.timezone.utc)),
        ),
    ]
