# Generated by Django 4.1.2 on 2023-01-29 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_receptura_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptura',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
