# Generated by Django 4.1.2 on 2023-01-29 11:16

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_receptura_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptura',
            name='date',
            field=models.DateTimeField(default=recipe.models.get_time),
        ),
    ]
