# Generated by Django 4.1.2 on 2023-03-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_receptura_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licznik_receptur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_receptur', models.IntegerField(default=0)),
            ],
        ),
    ]
