# Generated by Django 4.1.2 on 2023-03-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_receptura_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='receptura',
            managers=[
            ],
        ),
    ]
