# Generated by Django 4.1.2 on 2025-12-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_receptura_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladnik',
            name='skladnik',
            field=models.CharField(max_length=50),
        ),
    ]
